services:
  # Backend Service
  - type: web
    name: streamconnect-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CLIENT_URL
        fromService:
          type: web
          name: streamconnect-frontend
          property: host
    healthCheckPath: /api/health

  # Frontend Service  
  - type: web
    name: streamconnect-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: streamconnect-backend
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html